services:
  postgres:
    image: postgres:15
    container_name: noteapp-postgres
    environment:
      POSTGRES_DB: ${DOCKER_DB_NAME}
      POSTGRES_USER: ${DOCKER_DB_USERNAME}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOCKER_DB_USERNAME} -d ${DOCKER_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: noteapp-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${DOCKER_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_DB_PASSWORD}
      JWT_SECRET_COMPOSE: ${JWT_SECRET}
      JWT_LIFE_TIME_COMPOSE: ${JWT_LIFE_TIME}
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: