GRANT ALL PRIVILEGES ON DATABASE noteapp TO admin;
ALTER SCHEMA public OWNER TO admin;
GRANT ALL ON SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;
